#!/usr/bin/env bash
# Register Chrome Native Messaging host so the extension can auto-start the bridge.
#
#   ./scripts/install-native-host.sh install
#   ./scripts/install-native-host.sh uninstall
#   ./scripts/install-native-host.sh status
#
# Also works under Windows Git Bash by writing HKCU via reg.exe / powershell.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
HOST_NAME="com.leaf76.hermes_chrome"
HOST_PY="${ROOT}/native_host/host.py"
TEMPLATE="${ROOT}/native_host/${HOST_NAME}.json.template"
RUN_DIR="${HERMES_CHROME_RUN:-$HOME/.hermes/run/hermes-chrome}"
INSTALLED_MANIFEST="${RUN_DIR}/native-messaging/${HOST_NAME}.json"
WRAPPER="${RUN_DIR}/native-messaging/run-host"
EXTRA_EXT_ID="${HERMES_CHROME_EXTRA_EXTENSION_ID:-00000000000000000000000000000000}"

die() { echo "error: $*" >&2; exit 1; }
log() { echo "[hermes-chrome] $*"; }

PYTHON3="$(command -v python3 || command -v python || true)"
[[ -n "$PYTHON3" ]] || die "python3 not found"
[[ -f "$HOST_PY" ]] || die "missing $HOST_PY"
[[ -f "$TEMPLATE" ]] || die "missing $TEMPLATE"

uname_s="$(uname -s 2>/dev/null || echo unknown)"

write_wrapper() {
  mkdir -p "$(dirname "$WRAPPER")"
  if [[ "$uname_s" == MINGW* || "$uname_s" == MSYS* || "$uname_s" == CYGWIN* || "$uname_s" == Windows* ]]; then
    # Chrome on Windows: host path should be .bat/.cmd/.exe
    WRAPPER="${RUN_DIR}/native-messaging/run-host.bat"
    # Convert to Windows path for the bat body
    local py_win host_win
    py_win="$(cygpath -w "$PYTHON3" 2>/dev/null || echo "$PYTHON3")"
    host_win="$(cygpath -w "$HOST_PY" 2>/dev/null || echo "$HOST_PY")"
    cat >"$WRAPPER" <<EOF
@echo off
REM Auto-generated by install-native-host.sh — do not commit.
set HERMES_CHROME_ROOT=$(cygpath -w "$ROOT" 2>/dev/null || echo "$ROOT")
set HERMES_CHROME_RUN=$(cygpath -w "$RUN_DIR" 2>/dev/null || echo "$RUN_DIR")
"$py_win" -u "$host_win"
EOF
  else
    cat >"$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-native-host.sh — do not commit.
export HERMES_CHROME_ROOT="$ROOT"
export HERMES_CHROME_RUN="$RUN_DIR"
exec "$PYTHON3" -u "$HOST_PY"
EOF
    chmod +x "$WRAPPER"
  fi
}

write_manifest() {
  mkdir -p "$(dirname "$INSTALLED_MANIFEST")"
  local host_path="$WRAPPER"
  if [[ "$uname_s" == MINGW* || "$uname_s" == MSYS* || "$uname_s" == CYGWIN* ]]; then
    host_path="$(cygpath -w "$WRAPPER" 2>/dev/null || echo "$WRAPPER")"
    # JSON needs escaped backslashes
    host_path="${host_path//\\/\\\\}"
  fi
  sed \
    -e "s|__HOST_PATH__|${host_path}|g" \
    -e "s|__EXTRA_EXTENSION_ID__|${EXTRA_EXT_ID}|g" \
    "$TEMPLATE" >"$INSTALLED_MANIFEST"
  # Drop dummy extra origin if not set
  if [[ "$EXTRA_EXT_ID" == "00000000000000000000000000000000" ]]; then
    python3 - <<'PY' "$INSTALLED_MANIFEST"
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
obj = json.loads(p.read_text(encoding="utf-8"))
obj["allowed_origins"] = [
    o for o in obj.get("allowed_origins", [])
    if "00000000000000000000000000000000" not in o
]
p.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")
PY
  fi
}

chrome_nm_dirs() {
  # Paths where Chromium-family looks for native messaging host manifests.
  local dirs=()
  case "$uname_s" in
    Darwin)
      dirs+=(
        "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
        "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
        "$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
        "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      )
      ;;
    Linux)
      dirs+=(
        "$HOME/.config/google-chrome/NativeMessagingHosts"
        "$HOME/.config/chromium/NativeMessagingHosts"
        "$HOME/.config/microsoft-edge/NativeMessagingHosts"
        "$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      )
      ;;
    MINGW*|MSYS*|CYGWIN*|Windows*)
      # Windows uses registry; still keep a copy under RUN_DIR.
      ;;
  esac
  printf '%s\n' "${dirs[@]}"
}

register_unix() {
  local d link
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    mkdir -p "$d"
    link="${d}/${HOST_NAME}.json"
    ln -sfn "$INSTALLED_MANIFEST" "$link" 2>/dev/null || cp "$INSTALLED_MANIFEST" "$link"
    log "registered: $link"
  done < <(chrome_nm_dirs)
}

register_windows() {
  # HKCU for Chrome / Edge / Brave / Chromium
  local manifest_win
  manifest_win="$(cygpath -w "$INSTALLED_MANIFEST" 2>/dev/null || echo "$INSTALLED_MANIFEST")"
  local keys=(
    "HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\${HOST_NAME}"
    "HKCU\\Software\\Chromium\\NativeMessagingHosts\\${HOST_NAME}"
    "HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\${HOST_NAME}"
    "HKCU\\Software\\BraveSoftware\\Brave\\NativeMessagingHosts\\${HOST_NAME}"
  )
  local k
  for k in "${keys[@]}"; do
    reg.exe add "$k" /ve /t REG_SZ /d "$manifest_win" /f >/dev/null 2>&1 || true
    log "registry: $k"
  done
}

unregister_unix() {
  local d link
  while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    link="${d}/${HOST_NAME}.json"
    rm -f "$link"
  done < <(chrome_nm_dirs)
  rm -f "$INSTALLED_MANIFEST" "$WRAPPER" "${RUN_DIR}/native-messaging/run-host.bat" 2>/dev/null || true
  log "unregistered unix host files"
}

unregister_windows() {
  local keys=(
    "HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\${HOST_NAME}"
    "HKCU\\Software\\Chromium\\NativeMessagingHosts\\${HOST_NAME}"
    "HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\${HOST_NAME}"
    "HKCU\\Software\\BraveSoftware\\Brave\\NativeMessagingHosts\\${HOST_NAME}"
  )
  local k
  for k in "${keys[@]}"; do
    reg.exe delete "$k" /f >/dev/null 2>&1 || true
  done
  rm -f "$INSTALLED_MANIFEST" "${RUN_DIR}/native-messaging/run-host.bat" 2>/dev/null || true
  log "unregistered windows host"
}

cmd_install() {
  write_wrapper
  write_manifest
  if [[ "$uname_s" == MINGW* || "$uname_s" == MSYS* || "$uname_s" == CYGWIN* ]]; then
    register_windows
  else
    register_unix
  fi
  log "native host installed: $HOST_NAME"
  log "manifest: $INSTALLED_MANIFEST"
  log "wrapper:  $WRAPPER"
  log "Reload Hermes Chrome extension, click icon once."
}

cmd_uninstall() {
  if [[ "$uname_s" == MINGW* || "$uname_s" == MSYS* || "$uname_s" == CYGWIN* ]]; then
    unregister_windows
  else
    unregister_unix
  fi
}

cmd_status() {
  echo "host_name: $HOST_NAME"
  echo "manifest:  $INSTALLED_MANIFEST ($( [[ -f $INSTALLED_MANIFEST ]] && echo present || echo missing ))"
  echo "wrapper:   $WRAPPER ($( [[ -f $WRAPPER || -f ${RUN_DIR}/native-messaging/run-host.bat ]] && echo present || echo missing ))"
  if [[ "$uname_s" == Darwin || "$uname_s" == Linux ]]; then
    chrome_nm_dirs | while read -r d; do
      [[ -z "$d" ]] && continue
      echo "chrome_dir: $d/$( [[ -e $d/$HOST_NAME.json ]] && echo OK || echo — ) $d/${HOST_NAME}.json"
    done
  fi
}

case "${1:-install}" in
  install) cmd_install ;;
  uninstall) cmd_uninstall ;;
  status) cmd_status ;;
  *) die "usage: $0 install|uninstall|status" ;;
esac
