#Requires -Version 5.1
<#
.SYNOPSIS
  Register Chrome Native Messaging host (Windows) so Hermes Chrome can auto-start the bridge.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\scripts\install-native-host.ps1
  powershell -ExecutionPolicy Bypass -File .\scripts\install-native-host.ps1 -Uninstall
#>
param(
  [switch]$Uninstall,
  [string]$ExtraExtensionId = ""
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$HostName = "com.leaf76.hermes_chrome"
$HostPy = Join-Path $Root "native_host\host.py"
$Template = Join-Path $Root "native_host\$HostName.json.template"
$RunDir = Join-Path $env:USERPROFILE ".hermes\run\hermes-chrome"
$NmDir = Join-Path $RunDir "native-messaging"
$ManifestOut = Join-Path $NmDir "$HostName.json"
$WrapperBat = Join-Path $NmDir "run-host.bat"

function Write-Info($m) { Write-Host "[hermes-chrome] $m" }
function Die($m) { Write-Error $m; exit 1 }

function Find-Python {
  if (Get-Command py -ErrorAction SilentlyContinue) {
    try {
      $p = & py -3 -c "import sys; print(sys.executable)" 2>$null
      if ($p -and ($p -notmatch 'WindowsApps')) { return $p.Trim() }
    } catch {}
  }
  foreach ($name in @("python", "python3")) {
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Source -and ($cmd.Source -notmatch 'WindowsApps')) {
      return $cmd.Source
    }
  }
  foreach ($p in @(
      "$env:LOCALAPPDATA\Programs\Python\Python313\python.exe",
      "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
      "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe"
    )) {
    if (Test-Path $p) { return $p }
  }
  return $null
}

function Unregister-Host {
  $keys = @(
    "HKCU:\Software\Google\Chrome\NativeMessagingHosts\$HostName",
    "HKCU:\Software\Chromium\NativeMessagingHosts\$HostName",
    "HKCU:\Software\Microsoft\Edge\NativeMessagingHosts\$HostName",
    "HKCU:\Software\BraveSoftware\Brave\NativeMessagingHosts\$HostName"
  )
  foreach ($k in $keys) {
    if (Test-Path $k) { Remove-Item $k -Recurse -Force -ErrorAction SilentlyContinue }
  }
  Write-Info "registry keys removed"
}

if ($Uninstall) {
  Unregister-Host
  exit 0
}

if (-not (Test-Path $HostPy)) { Die "missing $HostPy" }
if (-not (Test-Path $Template)) { Die "missing $Template" }
$py = Find-Python
if (-not $py) {
  Die "No real Python 3 found. Install from https://www.python.org/downloads/ (Add to PATH), then re-run."
}

New-Item -ItemType Directory -Force -Path $NmDir | Out-Null

# Wrapper bat — absolute python path; keep stdio clean for Chrome.
@"
@echo off
REM Auto-generated by install-native-host.ps1 — do not commit.
set HERMES_CHROME_ROOT=$Root
set HERMES_CHROME_RUN=$RunDir
"$py" -u "$HostPy"
"@ | Set-Content -Path $WrapperBat -Encoding ASCII

# Manifest with Windows path (JSON escapes)
$hostPathJson = $WrapperBat -replace '\\', '\\'
$origins = @(
  "chrome-extension://mkoaoadlkijccmmbkioagnlngbbeocfa/"
)
if ($ExtraExtensionId -and $ExtraExtensionId.Length -eq 32) {
  $origins += "chrome-extension://$ExtraExtensionId/"
}
$manifestObj = [ordered]@{
  name = $HostName
  description = "Hermes Chrome local companion — starts the HTTP bridge for agents"
  path = $WrapperBat
  type = "stdio"
  allowed_origins = $origins
}
$manifestObj | ConvertTo-Json -Depth 5 | Set-Content -Path $ManifestOut -Encoding UTF8

Unregister-Host
$regKeys = @(
  "HKCU:\Software\Google\Chrome\NativeMessagingHosts\$HostName",
  "HKCU:\Software\Chromium\NativeMessagingHosts\$HostName",
  "HKCU:\Software\Microsoft\Edge\NativeMessagingHosts\$HostName",
  "HKCU:\Software\BraveSoftware\Brave\NativeMessagingHosts\$HostName"
)
foreach ($k in $regKeys) {
  New-Item -Path $k -Force | Out-Null
  New-ItemProperty -Path $k -Name "(default)" -Value $ManifestOut -PropertyType String -Force | Out-Null
  Write-Info "registered $k"
}

Write-Info "manifest: $ManifestOut"
Write-Info "wrapper:  $WrapperBat"
Write-Info "python:   $py"
Write-Info "Reload Hermes Chrome, click the icon once — bridge should auto-start."
